### ISSUE TITLE
data fields display in editor but not in XML preview

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/bfe2#92]
A cataloger reported that she input a variety of fields in a description, but they do not display in the posted record. They also do not display in Marva when the record is re-loaded.

I have duplicated this behavior on preprod-3001.
https://preprod-3001.id.loc.gov/bfe2/editor/edit/e0811612

I updated the Date of Work (bf:originDate) and Moving Image Technique (bflc:movingImageTechnique) fields. They do not display in the XML preview and they do not display in the preprod database either, https://preprod-8210.id.loc.gov/resources/works/a4d148af-55bd-4e5d-81c3-66b119b9fdaf

**Comment by ntra00** [comment]
bflc:movingImageTechnique is not a valid property.

**Comment by jodiw01** [comment]
transferred to Gitlab
